; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32cam]
platform = platform = espressif32@6.1.0
board = esp32cam
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = COM7 
monitor_port = COM7
lib_deps =
    https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot/archive/refs/heads/master.zip
    bblanchon/ArduinoJson@^6.21.3
    esp32-camera